name: build gphoto2 linux
on: workflow_dispatch

jobs:
  build:
    name: build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Download libgphoto2
        run: wget -nv
          https://github.com/gphoto/libgphoto2/releases/download/v2.5.31/libgphoto2-2.5.31.tar.xz
          -O libgphoto2.tar.xz

      - name: Extract libgphoto2
        run: |
          mkdir $PWD/libgphoto2
          tar xf libgphoto2.tar.xz \
            --directory $PWD/libgphoto2 --strip-components=1

      - name: Build wheels
        # cibuildwheel@v3.x omits Python 3.6 & 3.7
        uses: pypa/cibuildwheel@v2.23.3
        env:
          CIBW_ARCHS: auto64
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux_2_28
          CIBW_BUILD: cp*-manylinux*
          CIBW_ENVIRONMENT: GPHOTO2_ROOT=$PWD/libgphoto2/local_install
          CIBW_TEST_COMMAND: >
            python3 -m gphoto2 -v &&
            python3 -m unittest discover {project}/tests -v
          CIBW_BEFORE_ALL: >
            yum install -y libusbx-devel libexif-devel libjpeg-turbo-devel
            gd-devel libcurl-devel libxml2-devel libtool-ltdl-devel &&
            pushd $PWD/libgphoto2 &&
            ./configure --prefix=$PWD/local_install --disable-internal-docs
            --enable-vusb &&
            make &&
            make install &&
            popd

      - name: Store results
        uses: actions/upload-artifact@v4
        with:
          name: linux-wheels-${{ matrix.os }}
          path: wheelhouse/*.whl
